all:
	cd adapter; make
	cd builder; make
	cd factory; make
	cd prototype; make
	cd singleton; make

clean:
	cd adapter; make clean
	cd builder; make clean
	cd factory; make clean
	cd prototype; make clean
	cd singleton; make clean

