all:
	cd adapter; make
	cd builder; make
	cd bridge; make
	cd composite; make
	cd decorator; make
	cd facade; make
	cd factory; make
	cd filter; make
	cd flyweight; make
	cd prototype; make
	cd proxy; make
	cd singleton; make
	cd chain; make
	cd command; make
	cd interpreter; make
	cd iterator; make
	cd mediator; make
	cd memento; make

clean:
	cd adapter; make clean
	cd builder; make clean
	cd bridge; make clean
	cd composite; make clean
	cd decorator; make clean
	cd facade; make clean
	cd factory; make clean
	cd filter; make clean
	cd flyweight; make clean
	cd prototype; make clean
	cd proxy; make clean
	cd singleton; make clean
	cd chain; make clean
	cd command; make clean
	cd interpreter; make clean
	cd iterator; make clean
	cd mediator; make clean
	cd memento; make clean

test:
	cd adapter; make test
	cd bridge; make test
	cd builder; make test
	cd composite; make test
	cd decorator; make test
	cd facade; make test
	cd factory; make test
	cd filter; make test
	cd flyweight; make test
	cd prototype; make test
	cd proxy; make test
	cd singleton; make test
	cd chain; make test
	cd command; make test
	cd interpreter; make test
	cd iterator; make test
	cd mediator; make test
	cd memento; make test

