all:
	cd adapter; make
	cd builder; make
	cd bridge; make
	cd factory; make
	cd prototype; make
	cd singleton; make
	cd composite; make

clean:
	cd adapter; make clean
	cd builder; make clean
	cd bridge; make clean
	cd factory; make clean
	cd prototype; make clean
	cd singleton; make clean
	cd composite; make clean

test:
	cd adapter; make test
	cd builder; make test
	cd bridge; make test
	cd factory; make test
	cd prototype; make test
	cd composite; make test

